openapi: 3.0.0
info:
    title: Text Mutation API
    version: 1.0.0

components:
    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT

security:
    - BearerAuth: []

paths:
    /init:
        get:
            summary: Generate a new user ID and return a JWT token
            operationId: initializeUser
            responses:
                "200":
                    description: Successfully initialized user
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    token:
                                        type: string
                                        description: JWT token for the user
                            example:
                                token: "hogehoge"
                "500":
                    description: Internal server error - user creation failed
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: "Error creating user"
    /mutate:
        post:
            summary: Mutate a text
            operationId: mutateText
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                targetText:
                                    type: array
                                    items:
                                        type: string
                                    description: Text to be mutated
                            required:
                                - targetText
            responses:
                "200":
                    description: Successfully mutated text
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    result:
                                        type: object
                                        properties:
                                            mutatedLength:
                                                type: integer
                                                description: The index of mutated contents
                            example:
                                result:
                                    mutatedLength: 2
                "400":
                    description: Invalid request - the request could not be understood due to malformed syntax or invalid data.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: "Invalid input data: image path missing"
                default:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        description: "A detailed error message."

    /result:
        post:
            summary: Update result with given data
            operationId: updateResult
            security:
                - BearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                isPublic:
                                    type: boolean
                                    description: Whether the result should be public
                                favoriteId:
                                    type: integer
                                    description: ID of the favorite diary entry
                            required:
                                - isPublic
                                - favoriteId
            responses:
                "200":
                    description: Successfully updated result
                    content:
                        application/json:
                            schema:
                                type: string
                                example: "Success"
                "400":
                    description: Invalid request - the request could not be understood due to malformed syntax or invalid data.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: "Invalid input data"
                "401":
                    description: Unauthorized - the request requires valid user authentication.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: "Invalid or missing JWT token"
                default:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        description: "A detailed error message."
