openapi: 3.0.0
info:
    title: Text Mutation API
    version: 1.0.0
    description: API to receive text data and return mutated text.

paths:
    /mutate3:
        post:
            summary: mutate a text
            operationId: mutateText
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                clientId:
                                    type: integer
                                    description: ID of the window where the text is located.
                                mutatedLength:
                                    type: integer
                                    description: Index of the text to be mutated.
                                targetText:
                                    type: array
                                    items:
                                        type: string
                                    description: Text to be mutated.
                            required:
                                - clientId
                                - mutatedLength
                                - targetText
            responses:
                "200":
                    description: Successfully mutated text
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    result:
                                        type: object
                                        properties:
                                            mutatedLength:
                                                type: integer
                                                description: text index in the contents
                                            mutatedText:
                                                type: array
                                                items:
                                                    type: string
                                                description: AI output from BE
                            example:
                                {
                                    result:
                                        {
                                            mutatedLength: 0,
                                            mutatedText:
                                                ["hoge.", "fuga.", "piyo.", "blar.", "fooooo."],
                                        },
                                }
                "400":
                    description: Invalid request - the request could not be understood due to malformed syntax or invalid data.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: "Invalid input data: image path missing"
                default:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        description: "A detailed error message."

components:
    securitySchemes:
        ApiKeyAuth:
            type: apiKey
            in: header
            name: X-Api-Key
security:
    - ApiKeyAuth: []
